import { StyleSheet, ImageBackground } from "react-native";
import { BUTTON_COLOR, PRIMARY_COLOR, SECONDARY_COLOR, TERTARY_COLOR } from "./defaultColors";

export const styles = StyleSheet.create({
  background: {
    flex: 1,
    resizeMode: "cover",
  },
  container: {
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 20,
  },
  title: {
    fontSize: 24,
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 20,
  },
  background1: {
    flex: 1,
    resizeMode: "cover",
  },
  container1: {
    alignItems: "center",
    justifyContent: "space-evenly",
    flex: 1,
  },
  container2: {
    backgroundColor: SECONDARY_COLOR,
    borderRadius: 15,
    justifyContent: "center",
  },

  textoSignIn: {
    fontSize: 30,
    margin: 5,
    textAlign: "center",
  },
  textinput1: {
    alignItems: "center",
    margin: 15,
    padding: 10,
    backgroundColor: "#f1f4f5",
    width: "95%",
    alignSelf: "center",
    borderRadius: 10,
  },
  textinput2: {
    alignItems: "center",
    margin: 15,
    padding: 10,
    backgroundColor: "#f1f4f5",
    width: "95%",
    alignSelf: "center",
    borderRadius: 10,
  },
  button: {
    padding: 10,
    backgroundColor: "#ddd",
    borderRadius: 5,
    alignContent: "center",
    justifyContent: "center",
    margin: "auto",
    height: "auto",
    width: "auto",
  },
  inputTextSignUp: {
    backgroundColor: "#f1f4f5",
    maxWidth: 400,
    padding: 15,
    borderRadius: 10,
    margin: 7,
    elevation: 3,
  },
  body: {
    backgroundColor: SECONDARY_COLOR,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 35,
    paddingTop: 40,
    paddingHorizontal: 35,
  },
  titlePrincipal: {
    fontSize: 17,
    fontWeight: "bold",
    color: TERTARY_COLOR,
    alignSelf: "center",
  },
  title1: {
    color: TERTARY_COLOR,
    fontSize: 25,
    paddingHorizontal: 15,
    fontWeight: "bold",
    paddingVertical: 30,
    backgroundColor: PRIMARY_COLOR,
    textAlign: "left",
    justifyContent: "center",
  },
  containerForm: {
    marginBottom: 10,
  },
  titleDescrption: {
    fontSize: 15,
    color: TERTARY_COLOR,
    marginTop: 7,
    alignSelf: "center",
  },
  buttomForm: {
    backgroundColor: BUTTON_COLOR,
    paddingVertical: 10,
    paddingHorizontal: 10,
    alignItems: "center",
    borderRadius: 10,
    elevation: 3,
    width: "95%",
    maxWidth: 400,
    margin: 10,
    cursor: "pointer",
  },
  register: {
    alignSelf: "center",
    color: "grey",
    fontWeight: "condensed",
    margin: 10,
  },
  sub: {
    textDecorationLine: "underline",
  },
  iconPassword: {
    position: "absolute",
    right: 20,
    bottom: 25,
  },
  //estilos con nombre sin necesidad de renombrar
  containerCard: {
    flex: 1,
    width: 160,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
    shadowColor: "#000",
    shadowOpacity: 0.25,
    shadowRadius: 2.7,
    borderWidth: 1,
    borderColor: PRIMARY_COLOR,
    borderStyle: "solid",
    marginBottom: 15,
    elevation: 2,
    marginRight: 5,
  },
  cardImage: {
    height: 100,
    width: 100,
  },
  titleCard: {
    fontSize: 15,
    fontWeight: "bold",
    color: TERTARY_COLOR,
  },
  containerIcon: {
    flex: 1,
    marginTop: 15,
    alignSelf: "flex-end",
  },
});
