import { StyleSheet, ImageBackground } from "react-native";

export const styles = StyleSheet.create({
  background: {
    flex: 1,
    resizeMode: "cover",
  },
  container: {
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 20,
  },
  title: {
    fontSize: 24,
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 20,
  },
  background1: {
    flex: 1,
    resizeMode: "cover",
  },
  container1: {
    alignItems: "center",
    justifyContent: "space-evenly",
    flex: 1,
  },
  container2: {
    backgroundColor: "white",
    borderRadius: 15,
    justifyContent: "center",
  },

  textoSignIn: {
    fontSize: 30,
    margin: 5,
    textAlign: "center",
  },
  textinput1: {
    alignItems: "center",
    margin: 15,
    padding: 10,
    backgroundColor: "#f1f4f5",
    width: "95%",
    alignSelf: "center",
    borderRadius: 10,
  },
  textinput2: {
    alignItems: "center",
    margin: 15,
    padding: 10,
    backgroundColor: "#f1f4f5",
    width: "95%",
    alignSelf: "center",
    borderRadius: 10,
  },
  button: {
    padding: 10,
    backgroundColor: "#ddd",
    borderRadius: 5,
    alignContent: "center",
    justifyContent: "center",
    margin: "auto",
    height: "auto",
    width: "auto",
  },
  inputTextSignUp: {
    backgroundColor: "#f1f4f5",
    maxWidth: 400,
    padding: 15,
    borderRadius: 10,
    margin: 7,
    elevation: 3,
  },
  body: {
    backgroundColor: "white",
    borderTopLeftRadius: 30,
    borderTopRightRadius: 35,
    paddingTop: 40,
    paddingHorizontal: 35,
  },
  titlePrincipal: {
    fontSize: 17,
    fontWeight: "bold",
    color: "blacks",
    alignSelf: "center",
  },
  title1: {
    color: "black",
    fontSize: 25,
    paddingHorizontal: 15,
    fontWeight: "bold",
    paddingVertical: 30,
    backgroundColor: "#D1F8EF",
    textAlign: "left",
    justifyContent: "center",
  },
  containerForm: {
    marginBottom: 10,
  },
  titleDescrption: {
    fontSize: 15,
    color: "black",
    marginTop: 7,
    alignSelf: "center",
  },
  buttomForm: {
    backgroundColor: "#D0F3F7",
    paddingVertical: 10,
    paddingHorizontal: 10,
    alignItems: "center",
    borderRadius: 10,
    elevation: 3,
    width: "95%",
    maxWidth: 400,
    margin: 10,
    cursor: "pointer",
  },
  register: {
    alignSelf: "center",
    color: "grey",
    fontWeight: "condensed",
    margin: 10,
  },
  sub: {
    textDecorationLine: "underline",
  },
  iconPassword: {
    position: "absolute",
    right: 20,
    bottom: 25,
  },
});
